version: '3.8'

services:
 
  database:
    image: mongo:6.0
    container_name: mern_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

 
  backend:
    build: ./backend
    container_name: mern_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://database:27017/my_database 
    depends_on:
      - database 

 
  frontend:
    build: ./frontend
    container_name: mern_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: